### ISSUE TITLE
undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

### ISSUE THREAD

**Issue by nikogamulin** [hszhao/PointWeb#4]
When I try to run `sh tool/train.sh s3dis pointweb`, I get the following error:
```
[2020-02-06 23:16:49,255 INFO train.py line 65 10012] arch: pointweb_seg
base_lr: 0.05
block_size: 1.0
classes: 13
data_name: s3dis
data_root: dataset/s3dis
epochs: 100
evaluate: True
fea_dim: 6
ignore_label: 255
manual_seed: None
model_path: exp/s3dis/pointweb/model/train_epoch_100.pth
momentum: 0.9
multiplier: 0.1
names_path: data/s3dis/s3dis_names.txt
num_point: 4096
print_freq: 10
resume: None
sample_rate: 1.0
save_folder: exp/s3dis/pointweb/result/epoch_100/val5_0.5
save_freq: 1
save_path: exp/s3dis/pointweb/model
split: val
start_epoch: 0
step_epoch: 30
stride_rate: 0.5
sync_bn: False
test_area: 5
test_batch_size: 8
test_gpu: [0]
test_list: dataset/s3dis/list/val5.txt
test_list_full: dataset/s3dis/list/val5_full.txt
test_workers: 4
train_batch_size: 16
train_batch_size_val: 8
train_full_folder: dataset/s3dis/trainval_fullarea
train_gpu: [0]
train_list: dataset/s3dis/list/train12346.txt
train_workers: 8
use_xyz: True
val_list: dataset/s3dis/list/val5.txt
weight: None
weight_decay: 0.0001
Traceback (most recent call last):
  File "tool/train.py", line 274, in <module>
    main()
  File "tool/train.py", line 75, in main
    from model.pointweb.pointweb_seg import PointWebSeg as Model
  File "/home/niko/workspace/PointWeb/model/pointweb/pointweb_seg.py", line 6, in <module>
    from model.pointweb.pointweb_module import PointWebSAModule
  File "/home/niko/workspace/PointWeb/model/pointweb/pointweb_module.py", line 7, in <module>
    from lib.pointops.functions import pointops
  File "/home/niko/workspace/PointWeb/lib/pointops/functions/pointops.py", line 7, in <module>
    import pointops_cuda
ImportError: /home/niko/workspace/PointWeb/venv/lib/python3.6/site-packages/pointops-0.0.0-py3.6-linux-x86_64.egg/pointops_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
[2020-02-06 23:16:49,622 INFO test_s3dis.py line 49 10025] arch: pointweb_seg
base_lr: 0.05
block_size: 1.0
classes: 13
data_name: s3dis
data_root: dataset/s3dis
epochs: 100
evaluate: True
fea_dim: 6
ignore_label: 255
manual_seed: None
model_path: exp/s3dis/pointweb/model/train_epoch_100.pth
momentum: 0.9
multiplier: 0.1
names_path: data/s3dis/s3dis_names.txt
num_point: 4096
print_freq: 10
resume: None
sample_rate: 1.0
save_folder: exp/s3dis/pointweb/result/epoch_100/val5_0.5
save_freq: 1
save_path: exp/s3dis/pointweb/model
split: val
start_epoch: 0
step_epoch: 30
stride_rate: 0.5
sync_bn: True
test_area: 5
test_batch_size: 8
test_gpu: [0]
test_list: dataset/s3dis/list/val5.txt
test_list_full: dataset/s3dis/list/val5_full.txt
test_workers: 4
train_batch_size: 16
train_batch_size_val: 8
train_full_folder: dataset/s3dis/trainval_fullarea
train_gpu: [0]
train_list: dataset/s3dis/list/train12346.txt
train_workers: 8
use_xyz: True
val_list: dataset/s3dis/list/val5.txt
weight: None
weight_decay: 0.0001
[2020-02-06 23:16:49,622 INFO test_s3dis.py line 51 10025] => creating model ...
[2020-02-06 23:16:49,622 INFO test_s3dis.py line 52 10025] Classes: 13
Traceback (most recent call last):
  File "tool/test_s3dis.py", line 216, in <module>
    main()
  File "tool/test_s3dis.py", line 59, in main
    from model.pointweb.pointweb_seg import PointWebSeg as Model
  File "/home/niko/workspace/PointWeb/model/pointweb/pointweb_seg.py", line 6, in <module>
    from model.pointweb.pointweb_module import PointWebSAModule
  File "/home/niko/workspace/PointWeb/model/pointweb/pointweb_module.py", line 7, in <module>
    from lib.pointops.functions import pointops
  File "/home/niko/workspace/PointWeb/lib/pointops/functions/pointops.py", line 7, in <module>
    import pointops_cuda
ImportError: /home/niko/workspace/PointWeb/venv/lib/python3.6/site-packages/pointops-0.0.0-py3.6-linux-x86_64.egg/pointops_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
```

**Comment by yuan-zm** [comment]
When I using pytorch==1.3.1, it never reports this error.

**Comment by zkm98** [comment]
this shows an error while you compile the tool about the pointnet++ part
